### ISSUE TITLE
Need Whiteboxgis available in the container

### ISSUE THREAD

**Issue by Ash-Manoj** [VForWaTer/tool_whiteboxgis#1]
To run the tools, we need the Whiteboxgis executable.
Executable is here: https://www.whiteboxgeo.com/WBT_Linux/WhiteboxTools_linux_amd64.zip
Download instructions are here: https://www.whiteboxgeo.com/download-direct/

I am not sure how to proceed here, help is appreciated @mmaelicke @AlexDo1

**Comment by AlexDo1** [comment]
Here is a docker image for whitebox-tools: https://hub.docker.com/r/webmapp/docker-whitebox-tools

But the image is 5 years old and I don't know if it is usable for us.
